djangoproject/testdjango/testdjango/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from testmodel import urls
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^testmodel/',include('testmodel.urls',namespace='testmodel'))
]

djangoproject/testdjango/testmodel/urls.py
from django.conf.urls import url
from .views import  index,adddb
from . import views
urlpatterns=[
    url('index/',index,name='index'),
    url(r'adddb',adddb,name='adddb'),
    url(r'private',views.private),
    url(r'allname',views.allname,name='allname')
]

djangoproject/testdjango/testmodel/models.py
#coding=utf8
from django.db import models
import datetime
import django
# Create your models here.

class Test(models.Model):
    name=models.CharField(max_length=50,null=True)
    age=models.IntegerField(null=True)
    def __str__(self):
        return self.name


class Topic(models.Model):
    name=models.CharField(max_length=30)
    add_date=models.DateTimeField(null=True,auto_now=True)
    def __str__(self):
        return self.name

class Article(models.Model):
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    content=models.TextField()
    def __str__(self):
        return self.content[:20]

djangoproject/testdjango/testmodel/forms.py
#coding=utf8

from django import forms
from  .models import Test
class NameForm(forms.ModelForm):
    class Meta:
        model=Test
        fields=['name','age']
        labels={'name':"请输入要存到数据库的姓名:",'age':'请输入年龄'}

djangoproject/testdjango/testmodel/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Test
from .forms import NameForm
import django
from django.core.urlresolvers import reverse
# Create your views here.
def index(response):
    return render(response,'index.html')

def adddb(request):
    if request.method=="GET":
        form=NameForm()
        return render(request,'addname.html',{'form':form})
    name=request.POST.get('name','detaulst')
    age=request.POST.get('age',0)
    print(name)
    test=Test(name=name,age=age)
    test.save()
    return django.http.HttpResponseRedirect(reverse("testmodel:allname"))
    return HttpResponse("添加数据记录成功")
    pass
def private(request):
    return django.http.HttpResponseForbidden('<h1>Forbudden</h1>')


def allname(request):
    names=Test.objects.all().order_by('-id')
    return render(request,'allname.html',context={'names':names})

djangoproject/testdjango/testmodel/templates/addname.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加数据库</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button>提交</button>
</form>
</body>
</html>

djangoproject/testdjango/testmodel/templates/allname.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>全部人员</title>
</head>
<body>
{% for name in names %}
    <h1>{{name.name}}</h1><br>
{% endfor %}
</body>
</html>

djangoproject/testdjango/testmodel/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>您当前访问的url 是{% url 'testmodel:index' %}</h1>
<br>
<a href="{% url 'testmodel:adddb'%}">向数据库添加纪录</a>
</body>
</html>